// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Church struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Type          sql.NullString `json:"type"`
	AddressText   string         `json:"address_text"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	CountryCode   string         `json:"country_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Jurisdiction  sql.NullString `json:"jurisdiction"`
	Website       sql.NullString `json:"website"`
	Phone         sql.NullString `json:"phone"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type ChurchSource struct {
	ID       int64  `json:"id"`
	ChurchID int64  `json:"church_id"`
	Source   string `json:"source"`
}

type Relic struct {
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
	Description sql.NullString `json:"description"`
}

type Saint struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	FeastDay    sql.NullString `json:"feast_day"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	LivesUrl    sql.NullString `json:"lives_url"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
