// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Church struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	AddressText   string         `json:"address_text"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	CountryCode   string         `json:"country_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Jurisdiction  sql.NullString `json:"jurisdiction"`
	Website       sql.NullString `json:"website"`
	Description   sql.NullString `json:"description"`
}

type Relic struct {
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
	Description sql.NullString `json:"description"`
}

type Saint struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	FeastDay    sql.NullString `json:"feast_day"`
	Description sql.NullString `json:"description"`
}
