// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Admin struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	MfaSecret    sql.NullString `json:"mfa_secret"`
	MfaEnabled   sql.NullBool   `json:"mfa_enabled"`
	LastLoginAt  sql.NullTime   `json:"last_login_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Church struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Type          sql.NullString `json:"type"`
	AddressText   string         `json:"address_text"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	CountryCode   string         `json:"country_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Jurisdiction  sql.NullString `json:"jurisdiction"`
	Website       sql.NullString `json:"website"`
	Phone         sql.NullString `json:"phone"`
	Description   sql.NullString `json:"description"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	PostalCode    sql.NullString `json:"postal_code"`
	Status        string         `json:"status"`
}

type ChurchSource struct {
	ID       int64  `json:"id"`
	ChurchID int64  `json:"church_id"`
	Source   string `json:"source"`
}

type Image struct {
	ID            int64          `json:"id"`
	ChurchID      sql.NullInt64  `json:"church_id"`
	SaintID       sql.NullInt64  `json:"saint_id"`
	RelicChurchID sql.NullInt64  `json:"relic_church_id"`
	RelicSaintID  sql.NullInt64  `json:"relic_saint_id"`
	Url           string         `json:"url"`
	AltText       sql.NullString `json:"alt_text"`
	Source        sql.NullString `json:"source"`
	IsPrimary     sql.NullBool   `json:"is_primary"`
	SortOrder     sql.NullInt64  `json:"sort_order"`
}

type Relic struct {
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
	Description sql.NullString `json:"description"`
}

type Saint struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	FeastDay    sql.NullString `json:"feast_day"`
	Description sql.NullString `json:"description"`
	LivesUrl    sql.NullString `json:"lives_url"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Status      string         `json:"status"`
}

type Session struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}
