// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countChurches = `-- name: CountChurches :one
SELECT count(*) FROM churches
`

func (q *Queries) CountChurches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChurches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChurch = `-- name: CreateChurch :one
INSERT INTO churches (
    name,
    address_text,
    city,
    state_province,
    country_code,
    latitude,
    longitude,
    jurisdiction,
    website,
    description
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, description
`

type CreateChurchParams struct {
	Name          string         `json:"name"`
	AddressText   string         `json:"address_text"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	CountryCode   string         `json:"country_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Jurisdiction  sql.NullString `json:"jurisdiction"`
	Website       sql.NullString `json:"website"`
	Description   sql.NullString `json:"description"`
}

func (q *Queries) CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error) {
	row := q.db.QueryRowContext(ctx, createChurch,
		arg.Name,
		arg.AddressText,
		arg.City,
		arg.StateProvince,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.Jurisdiction,
		arg.Website,
		arg.Description,
	)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Description,
	)
	return i, err
}

const getChurch = `-- name: GetChurch :one
SELECT id, name, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, description FROM churches
WHERE id = ?
`

func (q *Queries) GetChurch(ctx context.Context, id int64) (Church, error) {
	row := q.db.QueryRowContext(ctx, getChurch, id)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Description,
	)
	return i, err
}

const listChurches = `-- name: ListChurches :many
SELECT id, name, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, description FROM churches
ORDER BY name
`

func (q *Queries) ListChurches(ctx context.Context) ([]Church, error) {
	rows, err := q.db.QueryContext(ctx, listChurches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Church
	for rows.Next() {
		var i Church
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
