// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountChurches(ctx context.Context) (int64, error)
	CountSaints(ctx context.Context) (int64, error)
	CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error)
	CreateRelic(ctx context.Context, arg CreateRelicParams) error
	CreateSaint(ctx context.Context, arg CreateSaintParams) (Saint, error)
	DeleteAllChurches(ctx context.Context) error
	DeleteAllRelics(ctx context.Context) error
	DeleteAllSaints(ctx context.Context) error
	GetChurch(ctx context.Context, id int64) (Church, error)
	GetChurchBySlug(ctx context.Context, slug string) (Church, error)
	GetSaintBySlug(ctx context.Context, slug string) (Saint, error)
	ListChurches(ctx context.Context) ([]Church, error)
	ListChurchesBySaintSlug(ctx context.Context, slug string) ([]Church, error)
	ListChurchesInBounds(ctx context.Context, arg ListChurchesInBoundsParams) ([]Church, error)
	ListRelicsForChurch(ctx context.Context, churchID int64) ([]ListRelicsForChurchRow, error)
}

var _ Querier = (*Queries)(nil)
