// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countChurches = `-- name: CountChurches :one
SELECT count(*) FROM churches
`

func (q *Queries) CountChurches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChurches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSaints = `-- name: CountSaints :one
SELECT count(*) FROM saints
`

func (q *Queries) CountSaints(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSaints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChurch = `-- name: CreateChurch :one
INSERT INTO churches (
    name,
    slug,
    type,
    address_text,
    city,
    state_province,
    country_code,
    latitude,
    longitude,
    jurisdiction,
    website,
    phone,
    description,
    image_url,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, slug, type, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, phone, description, image_url, updated_at
`

type CreateChurchParams struct {
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Type          sql.NullString `json:"type"`
	AddressText   string         `json:"address_text"`
	City          string         `json:"city"`
	StateProvince string         `json:"state_province"`
	CountryCode   string         `json:"country_code"`
	Latitude      float64        `json:"latitude"`
	Longitude     float64        `json:"longitude"`
	Jurisdiction  sql.NullString `json:"jurisdiction"`
	Website       sql.NullString `json:"website"`
	Phone         sql.NullString `json:"phone"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error) {
	row := q.db.QueryRowContext(ctx, createChurch,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.AddressText,
		arg.City,
		arg.StateProvince,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.Jurisdiction,
		arg.Website,
		arg.Phone,
		arg.Description,
		arg.ImageUrl,
		arg.UpdatedAt,
	)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Phone,
		&i.Description,
		&i.ImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const createChurchSource = `-- name: CreateChurchSource :exec
INSERT INTO church_sources (church_id, source) VALUES (?, ?)
`

type CreateChurchSourceParams struct {
	ChurchID int64  `json:"church_id"`
	Source   string `json:"source"`
}

func (q *Queries) CreateChurchSource(ctx context.Context, arg CreateChurchSourceParams) error {
	_, err := q.db.ExecContext(ctx, createChurchSource, arg.ChurchID, arg.Source)
	return err
}

const createRelic = `-- name: CreateRelic :exec
INSERT INTO relics (
    church_id,
    saint_id,
    description
) VALUES (
    ?, ?, ?
)
`

type CreateRelicParams struct {
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateRelic(ctx context.Context, arg CreateRelicParams) error {
	_, err := q.db.ExecContext(ctx, createRelic, arg.ChurchID, arg.SaintID, arg.Description)
	return err
}

const createSaint = `-- name: CreateSaint :one
INSERT INTO saints (
    name,
    slug,
    feast_day,
    description,
    image_url,
    lives_url,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, slug, feast_day, description, image_url, lives_url, updated_at
`

type CreateSaintParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	FeastDay    sql.NullString `json:"feast_day"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	LivesUrl    sql.NullString `json:"lives_url"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateSaint(ctx context.Context, arg CreateSaintParams) (Saint, error) {
	row := q.db.QueryRowContext(ctx, createSaint,
		arg.Name,
		arg.Slug,
		arg.FeastDay,
		arg.Description,
		arg.ImageUrl,
		arg.LivesUrl,
		arg.UpdatedAt,
	)
	var i Saint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FeastDay,
		&i.Description,
		&i.ImageUrl,
		&i.LivesUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllChurches = `-- name: DeleteAllChurches :exec
DELETE FROM churches
`

func (q *Queries) DeleteAllChurches(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChurches)
	return err
}

const deleteAllRelics = `-- name: DeleteAllRelics :exec
DELETE FROM relics
`

func (q *Queries) DeleteAllRelics(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRelics)
	return err
}

const deleteAllSaints = `-- name: DeleteAllSaints :exec
DELETE FROM saints
`

func (q *Queries) DeleteAllSaints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSaints)
	return err
}

const getChurch = `-- name: GetChurch :one
SELECT id, name, slug, type, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, phone, description, image_url, updated_at FROM churches
WHERE id = ?
`

func (q *Queries) GetChurch(ctx context.Context, id int64) (Church, error) {
	row := q.db.QueryRowContext(ctx, getChurch, id)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Phone,
		&i.Description,
		&i.ImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getChurchBySlug = `-- name: GetChurchBySlug :one
SELECT id, name, slug, type, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, phone, description, image_url, updated_at FROM churches
WHERE slug = ?
`

func (q *Queries) GetChurchBySlug(ctx context.Context, slug string) (Church, error) {
	row := q.db.QueryRowContext(ctx, getChurchBySlug, slug)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Phone,
		&i.Description,
		&i.ImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getSaintBySlug = `-- name: GetSaintBySlug :one
SELECT id, name, slug, feast_day, description, image_url, lives_url, updated_at FROM saints
WHERE slug = ?
`

func (q *Queries) GetSaintBySlug(ctx context.Context, slug string) (Saint, error) {
	row := q.db.QueryRowContext(ctx, getSaintBySlug, slug)
	var i Saint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FeastDay,
		&i.Description,
		&i.ImageUrl,
		&i.LivesUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const listChurches = `-- name: ListChurches :many
SELECT id, name, slug, type, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, phone, description, image_url, updated_at FROM churches
ORDER BY name
`

func (q *Queries) ListChurches(ctx context.Context) ([]Church, error) {
	rows, err := q.db.QueryContext(ctx, listChurches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Church
	for rows.Next() {
		var i Church
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.ImageUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurchesBySaintSlug = `-- name: ListChurchesBySaintSlug :many
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.image_url, c.updated_at FROM churches c
JOIN relics r ON c.id = r.church_id
JOIN saints s ON r.saint_id = s.id
WHERE s.slug = ?
ORDER BY c.name
`

func (q *Queries) ListChurchesBySaintSlug(ctx context.Context, slug string) ([]Church, error) {
	rows, err := q.db.QueryContext(ctx, listChurchesBySaintSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Church
	for rows.Next() {
		var i Church
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.ImageUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurchesInBounds = `-- name: ListChurchesInBounds :many
SELECT id, name, slug, type, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, phone, description, image_url, updated_at FROM churches
WHERE latitude >= ? AND latitude <= ?
  AND longitude >= ? AND longitude <= ?
ORDER BY name
`

type ListChurchesInBoundsParams struct {
	Latitude    float64 `json:"latitude"`
	Latitude_2  float64 `json:"latitude_2"`
	Longitude   float64 `json:"longitude"`
	Longitude_2 float64 `json:"longitude_2"`
}

func (q *Queries) ListChurchesInBounds(ctx context.Context, arg ListChurchesInBoundsParams) ([]Church, error) {
	rows, err := q.db.QueryContext(ctx, listChurchesInBounds,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Church
	for rows.Next() {
		var i Church
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.ImageUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelicsForChurch = `-- name: ListRelicsForChurch :many
SELECT s.id, s.name, s.slug, s.feast_day, s.description, s.image_url, s.lives_url, s.updated_at, r.description as relic_description
FROM saints s
JOIN relics r ON s.id = r.saint_id
WHERE r.church_id = ?
`

type ListRelicsForChurchRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	FeastDay         sql.NullString `json:"feast_day"`
	Description      sql.NullString `json:"description"`
	ImageUrl         sql.NullString `json:"image_url"`
	LivesUrl         sql.NullString `json:"lives_url"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	RelicDescription sql.NullString `json:"relic_description"`
}

func (q *Queries) ListRelicsForChurch(ctx context.Context, churchID int64) ([]ListRelicsForChurchRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelicsForChurch, churchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelicsForChurchRow
	for rows.Next() {
		var i ListRelicsForChurchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.ImageUrl,
			&i.LivesUrl,
			&i.UpdatedAt,
			&i.RelicDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaints = `-- name: ListSaints :many
SELECT id, name, slug, feast_day, description, image_url, lives_url, updated_at FROM saints
ORDER BY name
`

func (q *Queries) ListSaints(ctx context.Context) ([]Saint, error) {
	rows, err := q.db.QueryContext(ctx, listSaints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saint
	for rows.Next() {
		var i Saint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.ImageUrl,
			&i.LivesUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesForChurch = `-- name: ListSourcesForChurch :many
SELECT source FROM church_sources WHERE church_id = ?
`

func (q *Queries) ListSourcesForChurch(ctx context.Context, churchID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSourcesForChurch, churchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var source string
		if err := rows.Scan(&source); err != nil {
			return nil, err
		}
		items = append(items, source)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSaints = `-- name: SearchSaints :many
SELECT id, name, slug, feast_day, description, image_url, lives_url, updated_at FROM saints
WHERE name LIKE ?
ORDER BY name
LIMIT 10
`

func (q *Queries) SearchSaints(ctx context.Context, name string) ([]Saint, error) {
	rows, err := q.db.QueryContext(ctx, searchSaints, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saint
	for rows.Next() {
		var i Saint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.ImageUrl,
			&i.LivesUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
