// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countChurches = `-- name: CountChurches :one
SELECT count(*) FROM churches
`

func (q *Queries) CountChurches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChurches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRelics = `-- name: CountRelics :one
SELECT count(*) FROM relics
`

func (q *Queries) CountRelics(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRelics)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSaints = `-- name: CountSaints :one
SELECT count(*) FROM saints
`

func (q *Queries) CountSaints(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSaints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (
    username,
    password_hash,
    mfa_secret
) VALUES (
    ?, ?, ?
)
RETURNING id, username, password_hash, mfa_secret, mfa_enabled, last_login_at, created_at
`

type CreateAdminParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	MfaSecret    sql.NullString `json:"mfa_secret"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin, arg.Username, arg.PasswordHash, arg.MfaSecret)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const createChurch = `-- name: CreateChurch :one
INSERT INTO churches (
    name,
    slug,
    type,
    address_text,
    city,
    state_province,
    postal_code,
    country_code,
    latitude,
    longitude,
    jurisdiction_id,
    website,
    phone,
    description,
    status,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, slug, type, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, phone, description, updated_at, postal_code, status, jurisdiction_id
`

type CreateChurchParams struct {
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Type           sql.NullString `json:"type"`
	AddressText    string         `json:"address_text"`
	City           string         `json:"city"`
	StateProvince  string         `json:"state_province"`
	PostalCode     sql.NullString `json:"postal_code"`
	CountryCode    string         `json:"country_code"`
	Latitude       float64        `json:"latitude"`
	Longitude      float64        `json:"longitude"`
	JurisdictionID sql.NullInt64  `json:"jurisdiction_id"`
	Website        sql.NullString `json:"website"`
	Phone          sql.NullString `json:"phone"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error) {
	row := q.db.QueryRowContext(ctx, createChurch,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.AddressText,
		arg.City,
		arg.StateProvince,
		arg.PostalCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.JurisdictionID,
		arg.Website,
		arg.Phone,
		arg.Description,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Phone,
		&i.Description,
		&i.UpdatedAt,
		&i.PostalCode,
		&i.Status,
		&i.JurisdictionID,
	)
	return i, err
}

const createChurchSource = `-- name: CreateChurchSource :exec
INSERT INTO church_sources (church_id, source) VALUES (?, ?)
`

type CreateChurchSourceParams struct {
	ChurchID int64  `json:"church_id"`
	Source   string `json:"source"`
}

func (q *Queries) CreateChurchSource(ctx context.Context, arg CreateChurchSourceParams) error {
	_, err := q.db.ExecContext(ctx, createChurchSource, arg.ChurchID, arg.Source)
	return err
}

const createImage = `-- name: CreateImage :exec
INSERT INTO images (
    church_id,
    saint_id,
    relic_church_id,
    relic_saint_id,
    url,
    alt_text,
    source,
    is_primary,
    sort_order
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateImageParams struct {
	ChurchID      sql.NullInt64  `json:"church_id"`
	SaintID       sql.NullInt64  `json:"saint_id"`
	RelicChurchID sql.NullInt64  `json:"relic_church_id"`
	RelicSaintID  sql.NullInt64  `json:"relic_saint_id"`
	Url           string         `json:"url"`
	AltText       sql.NullString `json:"alt_text"`
	Source        sql.NullString `json:"source"`
	IsPrimary     sql.NullBool   `json:"is_primary"`
	SortOrder     sql.NullInt64  `json:"sort_order"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.ChurchID,
		arg.SaintID,
		arg.RelicChurchID,
		arg.RelicSaintID,
		arg.Url,
		arg.AltText,
		arg.Source,
		arg.IsPrimary,
		arg.SortOrder,
	)
	return err
}

const createJurisdiction = `-- name: CreateJurisdiction :one
INSERT INTO jurisdictions (name, tradition, pin_color) VALUES (?, ?, ?) RETURNING id, name, tradition, pin_color
`

type CreateJurisdictionParams struct {
	Name      string `json:"name"`
	Tradition string `json:"tradition"`
	PinColor  string `json:"pin_color"`
}

func (q *Queries) CreateJurisdiction(ctx context.Context, arg CreateJurisdictionParams) (Jurisdiction, error) {
	row := q.db.QueryRowContext(ctx, createJurisdiction, arg.Name, arg.Tradition, arg.PinColor)
	var i Jurisdiction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tradition,
		&i.PinColor,
	)
	return i, err
}

const createRelic = `-- name: CreateRelic :exec
INSERT INTO relics (
    church_id,
    saint_id,
    relic_type_id,
    description
) VALUES (
    ?, ?, ?, ?
)
`

type CreateRelicParams struct {
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
	RelicTypeID sql.NullInt64  `json:"relic_type_id"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateRelic(ctx context.Context, arg CreateRelicParams) error {
	_, err := q.db.ExecContext(ctx, createRelic,
		arg.ChurchID,
		arg.SaintID,
		arg.RelicTypeID,
		arg.Description,
	)
	return err
}

const createRelicType = `-- name: CreateRelicType :one
INSERT INTO relic_types (name, sort_order) VALUES (?, ?) RETURNING id, name, sort_order
`

type CreateRelicTypeParams struct {
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateRelicType(ctx context.Context, arg CreateRelicTypeParams) (RelicType, error) {
	row := q.db.QueryRowContext(ctx, createRelicType, arg.Name, arg.SortOrder)
	var i RelicType
	err := row.Scan(&i.ID, &i.Name, &i.SortOrder)
	return i, err
}

const createSaint = `-- name: CreateSaint :one
INSERT INTO saints (
    name,
    slug,
    feast_day,
    description,
    lives_url,
    status,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, slug, feast_day, description, lives_url, updated_at, status
`

type CreateSaintParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	FeastDay    sql.NullString `json:"feast_day"`
	Description sql.NullString `json:"description"`
	LivesUrl    sql.NullString `json:"lives_url"`
	Status      string         `json:"status"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateSaint(ctx context.Context, arg CreateSaintParams) (Saint, error) {
	row := q.db.QueryRowContext(ctx, createSaint,
		arg.Name,
		arg.Slug,
		arg.FeastDay,
		arg.Description,
		arg.LivesUrl,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Saint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FeastDay,
		&i.Description,
		&i.LivesUrl,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins WHERE id = ?
`

func (q *Queries) DeleteAdmin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAdmin, id)
	return err
}

const deleteAllChurches = `-- name: DeleteAllChurches :exec
DELETE FROM churches
`

func (q *Queries) DeleteAllChurches(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChurches)
	return err
}

const deleteAllImages = `-- name: DeleteAllImages :exec
DELETE FROM images
`

func (q *Queries) DeleteAllImages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllImages)
	return err
}

const deleteAllRelics = `-- name: DeleteAllRelics :exec
DELETE FROM relics
`

func (q *Queries) DeleteAllRelics(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRelics)
	return err
}

const deleteAllSaints = `-- name: DeleteAllSaints :exec
DELETE FROM saints
`

func (q *Queries) DeleteAllSaints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSaints)
	return err
}

const deleteAllSources = `-- name: DeleteAllSources :exec
DELETE FROM church_sources
`

func (q *Queries) DeleteAllSources(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSources)
	return err
}

const deleteChurch = `-- name: DeleteChurch :exec
DELETE FROM churches WHERE id = ?
`

func (q *Queries) DeleteChurch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChurch, id)
	return err
}

const deleteChurchSource = `-- name: DeleteChurchSource :exec
DELETE FROM church_sources WHERE id = ?
`

func (q *Queries) DeleteChurchSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChurchSource, id)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const deleteJurisdiction = `-- name: DeleteJurisdiction :exec
DELETE FROM jurisdictions WHERE id = ?
`

func (q *Queries) DeleteJurisdiction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJurisdiction, id)
	return err
}

const deleteRelic = `-- name: DeleteRelic :exec
DELETE FROM relics WHERE church_id = ? AND saint_id = ?
`

type DeleteRelicParams struct {
	ChurchID int64 `json:"church_id"`
	SaintID  int64 `json:"saint_id"`
}

func (q *Queries) DeleteRelic(ctx context.Context, arg DeleteRelicParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelic, arg.ChurchID, arg.SaintID)
	return err
}

const deleteRelicType = `-- name: DeleteRelicType :exec
DELETE FROM relic_types WHERE id = ?
`

func (q *Queries) DeleteRelicType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelicType, id)
	return err
}

const deleteSaint = `-- name: DeleteSaint :exec
DELETE FROM saints WHERE id = ?
`

func (q *Queries) DeleteSaint(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSaint, id)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, username, password_hash, mfa_secret, mfa_enabled, last_login_at, created_at FROM admins
WHERE id = ?
`

func (q *Queries) GetAdmin(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, mfa_secret, mfa_enabled, last_login_at, created_at FROM admins
WHERE username = ?
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChurch = `-- name: GetChurch :one
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.updated_at, c.postal_code, c.status, c.jurisdiction_id, j.name as jurisdiction_name, j.tradition, j.pin_color
FROM churches c
LEFT JOIN jurisdictions j ON c.jurisdiction_id = j.id
WHERE c.id = ?
`

type GetChurchRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Type             sql.NullString `json:"type"`
	AddressText      string         `json:"address_text"`
	City             string         `json:"city"`
	StateProvince    string         `json:"state_province"`
	CountryCode      string         `json:"country_code"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	Jurisdiction     sql.NullString `json:"jurisdiction"`
	Website          sql.NullString `json:"website"`
	Phone            sql.NullString `json:"phone"`
	Description      sql.NullString `json:"description"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	PostalCode       sql.NullString `json:"postal_code"`
	Status           string         `json:"status"`
	JurisdictionID   sql.NullInt64  `json:"jurisdiction_id"`
	JurisdictionName sql.NullString `json:"jurisdiction_name"`
	Tradition        sql.NullString `json:"tradition"`
	PinColor         sql.NullString `json:"pin_color"`
}

func (q *Queries) GetChurch(ctx context.Context, id int64) (GetChurchRow, error) {
	row := q.db.QueryRowContext(ctx, getChurch, id)
	var i GetChurchRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Phone,
		&i.Description,
		&i.UpdatedAt,
		&i.PostalCode,
		&i.Status,
		&i.JurisdictionID,
		&i.JurisdictionName,
		&i.Tradition,
		&i.PinColor,
	)
	return i, err
}

const getChurchBySlug = `-- name: GetChurchBySlug :one
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.updated_at, c.postal_code, c.status, c.jurisdiction_id, j.name as jurisdiction_name, j.tradition, j.pin_color
FROM churches c
LEFT JOIN jurisdictions j ON c.jurisdiction_id = j.id
WHERE c.slug = ?
`

type GetChurchBySlugRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Type             sql.NullString `json:"type"`
	AddressText      string         `json:"address_text"`
	City             string         `json:"city"`
	StateProvince    string         `json:"state_province"`
	CountryCode      string         `json:"country_code"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	Jurisdiction     sql.NullString `json:"jurisdiction"`
	Website          sql.NullString `json:"website"`
	Phone            sql.NullString `json:"phone"`
	Description      sql.NullString `json:"description"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	PostalCode       sql.NullString `json:"postal_code"`
	Status           string         `json:"status"`
	JurisdictionID   sql.NullInt64  `json:"jurisdiction_id"`
	JurisdictionName sql.NullString `json:"jurisdiction_name"`
	Tradition        sql.NullString `json:"tradition"`
	PinColor         sql.NullString `json:"pin_color"`
}

func (q *Queries) GetChurchBySlug(ctx context.Context, slug string) (GetChurchBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getChurchBySlug, slug)
	var i GetChurchBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Phone,
		&i.Description,
		&i.UpdatedAt,
		&i.PostalCode,
		&i.Status,
		&i.JurisdictionID,
		&i.JurisdictionName,
		&i.Tradition,
		&i.PinColor,
	)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT id, church_id, saint_id, relic_church_id, relic_saint_id, url, alt_text, source, is_primary, sort_order FROM images
WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.SaintID,
		&i.RelicChurchID,
		&i.RelicSaintID,
		&i.Url,
		&i.AltText,
		&i.Source,
		&i.IsPrimary,
		&i.SortOrder,
	)
	return i, err
}

const getJurisdiction = `-- name: GetJurisdiction :one
SELECT id, name, tradition, pin_color FROM jurisdictions WHERE id = ?
`

func (q *Queries) GetJurisdiction(ctx context.Context, id int64) (Jurisdiction, error) {
	row := q.db.QueryRowContext(ctx, getJurisdiction, id)
	var i Jurisdiction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tradition,
		&i.PinColor,
	)
	return i, err
}

const getRelicType = `-- name: GetRelicType :one
SELECT id, name, sort_order FROM relic_types WHERE id = ?
`

func (q *Queries) GetRelicType(ctx context.Context, id int64) (RelicType, error) {
	row := q.db.QueryRowContext(ctx, getRelicType, id)
	var i RelicType
	err := row.Scan(&i.ID, &i.Name, &i.SortOrder)
	return i, err
}

const getSaint = `-- name: GetSaint :one
SELECT id, name, slug, feast_day, description, lives_url, updated_at, status FROM saints
WHERE id = ?
`

func (q *Queries) GetSaint(ctx context.Context, id int64) (Saint, error) {
	row := q.db.QueryRowContext(ctx, getSaint, id)
	var i Saint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FeastDay,
		&i.Description,
		&i.LivesUrl,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getSaintBySlug = `-- name: GetSaintBySlug :one
SELECT id, name, slug, feast_day, description, lives_url, updated_at, status FROM saints
WHERE slug = ?
`

func (q *Queries) GetSaintBySlug(ctx context.Context, slug string) (Saint, error) {
	row := q.db.QueryRowContext(ctx, getSaintBySlug, slug)
	var i Saint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FeastDay,
		&i.Description,
		&i.LivesUrl,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, mfa_secret, mfa_enabled, last_login_at, created_at FROM admins
ORDER BY username
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.QueryContext(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admin
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.MfaSecret,
			&i.MfaEnabled,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRelics = `-- name: ListAllRelics :many
SELECT r.church_id, r.saint_id, r.description, r.relic_type_id, s.name as saint_name, c.name as church_name, rt.name as relic_type
FROM relics r
JOIN saints s ON r.saint_id = s.id
JOIN churches c ON r.church_id = c.id
LEFT JOIN relic_types rt ON r.relic_type_id = rt.id
ORDER BY c.name, s.name
`

type ListAllRelicsRow struct {
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
	Description sql.NullString `json:"description"`
	RelicTypeID sql.NullInt64  `json:"relic_type_id"`
	SaintName   string         `json:"saint_name"`
	ChurchName  string         `json:"church_name"`
	RelicType   sql.NullString `json:"relic_type"`
}

func (q *Queries) ListAllRelics(ctx context.Context) ([]ListAllRelicsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRelics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRelicsRow
	for rows.Next() {
		var i ListAllRelicsRow
		if err := rows.Scan(
			&i.ChurchID,
			&i.SaintID,
			&i.Description,
			&i.RelicTypeID,
			&i.SaintName,
			&i.ChurchName,
			&i.RelicType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurches = `-- name: ListChurches :many
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.updated_at, c.postal_code, c.status, c.jurisdiction_id, j.name as jurisdiction_name, j.tradition, j.pin_color
FROM churches c
LEFT JOIN jurisdictions j ON c.jurisdiction_id = j.id
ORDER BY c.name
`

type ListChurchesRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Type             sql.NullString `json:"type"`
	AddressText      string         `json:"address_text"`
	City             string         `json:"city"`
	StateProvince    string         `json:"state_province"`
	CountryCode      string         `json:"country_code"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	Jurisdiction     sql.NullString `json:"jurisdiction"`
	Website          sql.NullString `json:"website"`
	Phone            sql.NullString `json:"phone"`
	Description      sql.NullString `json:"description"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	PostalCode       sql.NullString `json:"postal_code"`
	Status           string         `json:"status"`
	JurisdictionID   sql.NullInt64  `json:"jurisdiction_id"`
	JurisdictionName sql.NullString `json:"jurisdiction_name"`
	Tradition        sql.NullString `json:"tradition"`
	PinColor         sql.NullString `json:"pin_color"`
}

func (q *Queries) ListChurches(ctx context.Context) ([]ListChurchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChurches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChurchesRow
	for rows.Next() {
		var i ListChurchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.UpdatedAt,
			&i.PostalCode,
			&i.Status,
			&i.JurisdictionID,
			&i.JurisdictionName,
			&i.Tradition,
			&i.PinColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurchesBySaintSlug = `-- name: ListChurchesBySaintSlug :many
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.updated_at, c.postal_code, c.status, c.jurisdiction_id, j.name as jurisdiction_name, j.tradition, j.pin_color
FROM churches c
JOIN relics r ON c.id = r.church_id
JOIN saints s ON r.saint_id = s.id
LEFT JOIN jurisdictions j ON c.jurisdiction_id = j.id
WHERE s.slug = ? AND c.status = 'published'
ORDER BY c.name
`

type ListChurchesBySaintSlugRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Type             sql.NullString `json:"type"`
	AddressText      string         `json:"address_text"`
	City             string         `json:"city"`
	StateProvince    string         `json:"state_province"`
	CountryCode      string         `json:"country_code"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	Jurisdiction     sql.NullString `json:"jurisdiction"`
	Website          sql.NullString `json:"website"`
	Phone            sql.NullString `json:"phone"`
	Description      sql.NullString `json:"description"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	PostalCode       sql.NullString `json:"postal_code"`
	Status           string         `json:"status"`
	JurisdictionID   sql.NullInt64  `json:"jurisdiction_id"`
	JurisdictionName sql.NullString `json:"jurisdiction_name"`
	Tradition        sql.NullString `json:"tradition"`
	PinColor         sql.NullString `json:"pin_color"`
}

func (q *Queries) ListChurchesBySaintSlug(ctx context.Context, slug string) ([]ListChurchesBySaintSlugRow, error) {
	rows, err := q.db.QueryContext(ctx, listChurchesBySaintSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChurchesBySaintSlugRow
	for rows.Next() {
		var i ListChurchesBySaintSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.UpdatedAt,
			&i.PostalCode,
			&i.Status,
			&i.JurisdictionID,
			&i.JurisdictionName,
			&i.Tradition,
			&i.PinColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurchesByStatus = `-- name: ListChurchesByStatus :many
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.updated_at, c.postal_code, c.status, c.jurisdiction_id, j.name as jurisdiction_name, j.tradition, j.pin_color
FROM churches c
LEFT JOIN jurisdictions j ON c.jurisdiction_id = j.id
WHERE c.status = ?
ORDER BY c.name
`

type ListChurchesByStatusRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Type             sql.NullString `json:"type"`
	AddressText      string         `json:"address_text"`
	City             string         `json:"city"`
	StateProvince    string         `json:"state_province"`
	CountryCode      string         `json:"country_code"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	Jurisdiction     sql.NullString `json:"jurisdiction"`
	Website          sql.NullString `json:"website"`
	Phone            sql.NullString `json:"phone"`
	Description      sql.NullString `json:"description"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	PostalCode       sql.NullString `json:"postal_code"`
	Status           string         `json:"status"`
	JurisdictionID   sql.NullInt64  `json:"jurisdiction_id"`
	JurisdictionName sql.NullString `json:"jurisdiction_name"`
	Tradition        sql.NullString `json:"tradition"`
	PinColor         sql.NullString `json:"pin_color"`
}

func (q *Queries) ListChurchesByStatus(ctx context.Context, status string) ([]ListChurchesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listChurchesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChurchesByStatusRow
	for rows.Next() {
		var i ListChurchesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.UpdatedAt,
			&i.PostalCode,
			&i.Status,
			&i.JurisdictionID,
			&i.JurisdictionName,
			&i.Tradition,
			&i.PinColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurchesInBounds = `-- name: ListChurchesInBounds :many
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.updated_at, c.postal_code, c.status, c.jurisdiction_id, j.name as jurisdiction_name, j.tradition, j.pin_color
FROM churches c
LEFT JOIN jurisdictions j ON c.jurisdiction_id = j.id
WHERE c.latitude >= ? AND c.latitude <= ?
  AND c.longitude >= ? AND c.longitude <= ?
  AND c.status = 'published'
ORDER BY c.name
`

type ListChurchesInBoundsParams struct {
	Latitude    float64 `json:"latitude"`
	Latitude_2  float64 `json:"latitude_2"`
	Longitude   float64 `json:"longitude"`
	Longitude_2 float64 `json:"longitude_2"`
}

type ListChurchesInBoundsRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Type             sql.NullString `json:"type"`
	AddressText      string         `json:"address_text"`
	City             string         `json:"city"`
	StateProvince    string         `json:"state_province"`
	CountryCode      string         `json:"country_code"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	Jurisdiction     sql.NullString `json:"jurisdiction"`
	Website          sql.NullString `json:"website"`
	Phone            sql.NullString `json:"phone"`
	Description      sql.NullString `json:"description"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	PostalCode       sql.NullString `json:"postal_code"`
	Status           string         `json:"status"`
	JurisdictionID   sql.NullInt64  `json:"jurisdiction_id"`
	JurisdictionName sql.NullString `json:"jurisdiction_name"`
	Tradition        sql.NullString `json:"tradition"`
	PinColor         sql.NullString `json:"pin_color"`
}

func (q *Queries) ListChurchesInBounds(ctx context.Context, arg ListChurchesInBoundsParams) ([]ListChurchesInBoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChurchesInBounds,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChurchesInBoundsRow
	for rows.Next() {
		var i ListChurchesInBoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.UpdatedAt,
			&i.PostalCode,
			&i.Status,
			&i.JurisdictionID,
			&i.JurisdictionName,
			&i.Tradition,
			&i.PinColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForChurch = `-- name: ListImagesForChurch :many
SELECT id, church_id, saint_id, relic_church_id, relic_saint_id, url, alt_text, source, is_primary, sort_order FROM images
WHERE church_id = ?
ORDER BY sort_order, id
`

func (q *Queries) ListImagesForChurch(ctx context.Context, churchID sql.NullInt64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesForChurch, churchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.SaintID,
			&i.RelicChurchID,
			&i.RelicSaintID,
			&i.Url,
			&i.AltText,
			&i.Source,
			&i.IsPrimary,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForRelic = `-- name: ListImagesForRelic :many
SELECT id, church_id, saint_id, relic_church_id, relic_saint_id, url, alt_text, source, is_primary, sort_order FROM images
WHERE relic_church_id = ? AND relic_saint_id = ?
ORDER BY sort_order, id
`

type ListImagesForRelicParams struct {
	RelicChurchID sql.NullInt64 `json:"relic_church_id"`
	RelicSaintID  sql.NullInt64 `json:"relic_saint_id"`
}

func (q *Queries) ListImagesForRelic(ctx context.Context, arg ListImagesForRelicParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesForRelic, arg.RelicChurchID, arg.RelicSaintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.SaintID,
			&i.RelicChurchID,
			&i.RelicSaintID,
			&i.Url,
			&i.AltText,
			&i.Source,
			&i.IsPrimary,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForSaint = `-- name: ListImagesForSaint :many
SELECT id, church_id, saint_id, relic_church_id, relic_saint_id, url, alt_text, source, is_primary, sort_order FROM images
WHERE saint_id = ?
ORDER BY sort_order, id
`

func (q *Queries) ListImagesForSaint(ctx context.Context, saintID sql.NullInt64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesForSaint, saintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.SaintID,
			&i.RelicChurchID,
			&i.RelicSaintID,
			&i.Url,
			&i.AltText,
			&i.Source,
			&i.IsPrimary,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJurisdictions = `-- name: ListJurisdictions :many
SELECT id, name, tradition, pin_color FROM jurisdictions ORDER BY name
`

func (q *Queries) ListJurisdictions(ctx context.Context) ([]Jurisdiction, error) {
	rows, err := q.db.QueryContext(ctx, listJurisdictions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jurisdiction
	for rows.Next() {
		var i Jurisdiction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tradition,
			&i.PinColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentChurches = `-- name: ListRecentChurches :many
SELECT c.id, c.name, c.slug, c.type, c.address_text, c.city, c.state_province, c.country_code, c.latitude, c.longitude, c.jurisdiction, c.website, c.phone, c.description, c.updated_at, c.postal_code, c.status, c.jurisdiction_id, j.name as jurisdiction_name, j.tradition, j.pin_color
FROM churches c
LEFT JOIN jurisdictions j ON c.jurisdiction_id = j.id
ORDER BY c.updated_at DESC NULLS LAST, c.id DESC
LIMIT 5
`

type ListRecentChurchesRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Type             sql.NullString `json:"type"`
	AddressText      string         `json:"address_text"`
	City             string         `json:"city"`
	StateProvince    string         `json:"state_province"`
	CountryCode      string         `json:"country_code"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	Jurisdiction     sql.NullString `json:"jurisdiction"`
	Website          sql.NullString `json:"website"`
	Phone            sql.NullString `json:"phone"`
	Description      sql.NullString `json:"description"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	PostalCode       sql.NullString `json:"postal_code"`
	Status           string         `json:"status"`
	JurisdictionID   sql.NullInt64  `json:"jurisdiction_id"`
	JurisdictionName sql.NullString `json:"jurisdiction_name"`
	Tradition        sql.NullString `json:"tradition"`
	PinColor         sql.NullString `json:"pin_color"`
}

func (q *Queries) ListRecentChurches(ctx context.Context) ([]ListRecentChurchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentChurches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentChurchesRow
	for rows.Next() {
		var i ListRecentChurchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.AddressText,
			&i.City,
			&i.StateProvince,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Jurisdiction,
			&i.Website,
			&i.Phone,
			&i.Description,
			&i.UpdatedAt,
			&i.PostalCode,
			&i.Status,
			&i.JurisdictionID,
			&i.JurisdictionName,
			&i.Tradition,
			&i.PinColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRelics = `-- name: ListRecentRelics :many
SELECT r.church_id, r.saint_id, r.description, r.relic_type_id, s.name as saint_name, c.name as church_name, rt.name as relic_type
FROM relics r
JOIN saints s ON r.saint_id = s.id
JOIN churches c ON r.church_id = c.id
LEFT JOIN relic_types rt ON r.relic_type_id = rt.id
ORDER BY c.updated_at DESC NULLS LAST
LIMIT 5
`

type ListRecentRelicsRow struct {
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
	Description sql.NullString `json:"description"`
	RelicTypeID sql.NullInt64  `json:"relic_type_id"`
	SaintName   string         `json:"saint_name"`
	ChurchName  string         `json:"church_name"`
	RelicType   sql.NullString `json:"relic_type"`
}

func (q *Queries) ListRecentRelics(ctx context.Context) ([]ListRecentRelicsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRelics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentRelicsRow
	for rows.Next() {
		var i ListRecentRelicsRow
		if err := rows.Scan(
			&i.ChurchID,
			&i.SaintID,
			&i.Description,
			&i.RelicTypeID,
			&i.SaintName,
			&i.ChurchName,
			&i.RelicType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSaints = `-- name: ListRecentSaints :many
SELECT id, name, slug, feast_day, description, lives_url, updated_at, status FROM saints
ORDER BY updated_at DESC NULLS LAST, id DESC
LIMIT 5
`

func (q *Queries) ListRecentSaints(ctx context.Context) ([]Saint, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSaints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saint
	for rows.Next() {
		var i Saint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.LivesUrl,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelicTypes = `-- name: ListRelicTypes :many
SELECT id, name, sort_order FROM relic_types ORDER BY sort_order
`

func (q *Queries) ListRelicTypes(ctx context.Context) ([]RelicType, error) {
	rows, err := q.db.QueryContext(ctx, listRelicTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelicType
	for rows.Next() {
		var i RelicType
		if err := rows.Scan(&i.ID, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelicsForChurch = `-- name: ListRelicsForChurch :many
SELECT s.id, s.name, s.slug, s.feast_day, s.description, s.lives_url, s.updated_at, s.status, r.description as relic_description, rt.name as relic_type, rt.id as relic_type_id
FROM saints s
JOIN relics r ON s.id = r.saint_id
LEFT JOIN relic_types rt ON r.relic_type_id = rt.id
WHERE r.church_id = ?
`

type ListRelicsForChurchRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	FeastDay         sql.NullString `json:"feast_day"`
	Description      sql.NullString `json:"description"`
	LivesUrl         sql.NullString `json:"lives_url"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	Status           string         `json:"status"`
	RelicDescription sql.NullString `json:"relic_description"`
	RelicType        sql.NullString `json:"relic_type"`
	RelicTypeID      sql.NullInt64  `json:"relic_type_id"`
}

func (q *Queries) ListRelicsForChurch(ctx context.Context, churchID int64) ([]ListRelicsForChurchRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelicsForChurch, churchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelicsForChurchRow
	for rows.Next() {
		var i ListRelicsForChurchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.LivesUrl,
			&i.UpdatedAt,
			&i.Status,
			&i.RelicDescription,
			&i.RelicType,
			&i.RelicTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaints = `-- name: ListSaints :many
SELECT id, name, slug, feast_day, description, lives_url, updated_at, status FROM saints
ORDER BY name
`

func (q *Queries) ListSaints(ctx context.Context) ([]Saint, error) {
	rows, err := q.db.QueryContext(ctx, listSaints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saint
	for rows.Next() {
		var i Saint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.LivesUrl,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaintsByStatus = `-- name: ListSaintsByStatus :many
SELECT id, name, slug, feast_day, description, lives_url, updated_at, status FROM saints
WHERE status = ?
ORDER BY name
`

func (q *Queries) ListSaintsByStatus(ctx context.Context, status string) ([]Saint, error) {
	rows, err := q.db.QueryContext(ctx, listSaintsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saint
	for rows.Next() {
		var i Saint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.LivesUrl,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesForChurch = `-- name: ListSourcesForChurch :many
SELECT id, church_id, source FROM church_sources WHERE church_id = ?
`

func (q *Queries) ListSourcesForChurch(ctx context.Context, churchID int64) ([]ChurchSource, error) {
	rows, err := q.db.QueryContext(ctx, listSourcesForChurch, churchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChurchSource
	for rows.Next() {
		var i ChurchSource
		if err := rows.Scan(&i.ID, &i.ChurchID, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSaints = `-- name: SearchSaints :many
SELECT id, name, slug, feast_day, description, lives_url, updated_at, status FROM saints
WHERE name LIKE ?
ORDER BY name
LIMIT 10
`

func (q *Queries) SearchSaints(ctx context.Context, name string) ([]Saint, error) {
	rows, err := q.db.QueryContext(ctx, searchSaints, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saint
	for rows.Next() {
		var i Saint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.FeastDay,
			&i.Description,
			&i.LivesUrl,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetPrimaryImageForChurch = `-- name: UnsetPrimaryImageForChurch :exec
UPDATE images SET is_primary = 0 WHERE church_id = ?
`

func (q *Queries) UnsetPrimaryImageForChurch(ctx context.Context, churchID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, unsetPrimaryImageForChurch, churchID)
	return err
}

const unsetPrimaryImageForSaint = `-- name: UnsetPrimaryImageForSaint :exec
UPDATE images SET is_primary = 0 WHERE saint_id = ?
`

func (q *Queries) UnsetPrimaryImageForSaint(ctx context.Context, saintID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, unsetPrimaryImageForSaint, saintID)
	return err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admins
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAdminLastLogin, id)
	return err
}

const updateAdminMFA = `-- name: UpdateAdminMFA :exec
UPDATE admins
SET mfa_secret = ?, mfa_enabled = ?
WHERE id = ?
`

type UpdateAdminMFAParams struct {
	MfaSecret  sql.NullString `json:"mfa_secret"`
	MfaEnabled sql.NullBool   `json:"mfa_enabled"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateAdminMFA(ctx context.Context, arg UpdateAdminMFAParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminMFA, arg.MfaSecret, arg.MfaEnabled, arg.ID)
	return err
}

const updateChurch = `-- name: UpdateChurch :one
UPDATE churches
SET name = ?,
    slug = ?,
    type = ?,
    address_text = ?,
    city = ?,
    state_province = ?,
    postal_code = ?,
    country_code = ?,
    latitude = ?,
    longitude = ?,
    jurisdiction_id = ?,
    website = ?,
    phone = ?,
    description = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, slug, type, address_text, city, state_province, country_code, latitude, longitude, jurisdiction, website, phone, description, updated_at, postal_code, status, jurisdiction_id
`

type UpdateChurchParams struct {
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Type           sql.NullString `json:"type"`
	AddressText    string         `json:"address_text"`
	City           string         `json:"city"`
	StateProvince  string         `json:"state_province"`
	PostalCode     sql.NullString `json:"postal_code"`
	CountryCode    string         `json:"country_code"`
	Latitude       float64        `json:"latitude"`
	Longitude      float64        `json:"longitude"`
	JurisdictionID sql.NullInt64  `json:"jurisdiction_id"`
	Website        sql.NullString `json:"website"`
	Phone          sql.NullString `json:"phone"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateChurch(ctx context.Context, arg UpdateChurchParams) (Church, error) {
	row := q.db.QueryRowContext(ctx, updateChurch,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.AddressText,
		arg.City,
		arg.StateProvince,
		arg.PostalCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.JurisdictionID,
		arg.Website,
		arg.Phone,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.AddressText,
		&i.City,
		&i.StateProvince,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Jurisdiction,
		&i.Website,
		&i.Phone,
		&i.Description,
		&i.UpdatedAt,
		&i.PostalCode,
		&i.Status,
		&i.JurisdictionID,
	)
	return i, err
}

const updateImage = `-- name: UpdateImage :exec
UPDATE images
SET alt_text = ?,
    is_primary = ?,
    sort_order = ?
WHERE id = ?
`

type UpdateImageParams struct {
	AltText   sql.NullString `json:"alt_text"`
	IsPrimary sql.NullBool   `json:"is_primary"`
	SortOrder sql.NullInt64  `json:"sort_order"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) error {
	_, err := q.db.ExecContext(ctx, updateImage,
		arg.AltText,
		arg.IsPrimary,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateJurisdiction = `-- name: UpdateJurisdiction :one
UPDATE jurisdictions
SET name = ?, tradition = ?, pin_color = ?
WHERE id = ?
RETURNING id, name, tradition, pin_color
`

type UpdateJurisdictionParams struct {
	Name      string `json:"name"`
	Tradition string `json:"tradition"`
	PinColor  string `json:"pin_color"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateJurisdiction(ctx context.Context, arg UpdateJurisdictionParams) (Jurisdiction, error) {
	row := q.db.QueryRowContext(ctx, updateJurisdiction,
		arg.Name,
		arg.Tradition,
		arg.PinColor,
		arg.ID,
	)
	var i Jurisdiction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tradition,
		&i.PinColor,
	)
	return i, err
}

const updateRelic = `-- name: UpdateRelic :exec
UPDATE relics
SET relic_type_id = ?,
    description = ?
WHERE church_id = ? AND saint_id = ?
`

type UpdateRelicParams struct {
	RelicTypeID sql.NullInt64  `json:"relic_type_id"`
	Description sql.NullString `json:"description"`
	ChurchID    int64          `json:"church_id"`
	SaintID     int64          `json:"saint_id"`
}

func (q *Queries) UpdateRelic(ctx context.Context, arg UpdateRelicParams) error {
	_, err := q.db.ExecContext(ctx, updateRelic,
		arg.RelicTypeID,
		arg.Description,
		arg.ChurchID,
		arg.SaintID,
	)
	return err
}

const updateRelicType = `-- name: UpdateRelicType :one
UPDATE relic_types
SET name = ?, sort_order = ?
WHERE id = ?
RETURNING id, name, sort_order
`

type UpdateRelicTypeParams struct {
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateRelicType(ctx context.Context, arg UpdateRelicTypeParams) (RelicType, error) {
	row := q.db.QueryRowContext(ctx, updateRelicType, arg.Name, arg.SortOrder, arg.ID)
	var i RelicType
	err := row.Scan(&i.ID, &i.Name, &i.SortOrder)
	return i, err
}

const updateSaint = `-- name: UpdateSaint :one
UPDATE saints
SET name = ?,
    slug = ?,
    feast_day = ?,
    description = ?,
    lives_url = ?,
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, slug, feast_day, description, lives_url, updated_at, status
`

type UpdateSaintParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	FeastDay    sql.NullString `json:"feast_day"`
	Description sql.NullString `json:"description"`
	LivesUrl    sql.NullString `json:"lives_url"`
	Status      string         `json:"status"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateSaint(ctx context.Context, arg UpdateSaintParams) (Saint, error) {
	row := q.db.QueryRowContext(ctx, updateSaint,
		arg.Name,
		arg.Slug,
		arg.FeastDay,
		arg.Description,
		arg.LivesUrl,
		arg.Status,
		arg.ID,
	)
	var i Saint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.FeastDay,
		&i.Description,
		&i.LivesUrl,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
