// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountChurches(ctx context.Context) (int64, error)
	CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error)
	GetChurch(ctx context.Context, id int64) (Church, error)
	ListChurches(ctx context.Context) ([]Church, error)
	ListChurchesInBounds(ctx context.Context, arg ListChurchesInBoundsParams) ([]Church, error)
}

var _ Querier = (*Queries)(nil)
